# Generated by Django 4.1.7 on 2023-03-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo1app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo1',
            name='date',
            field=models.DateField(default='1990-02-14'),
            preserve_default=False,
        ),
    ]
